---
- name: Install Apache2 and PHP
  remote_user: lylla
  hosts: webserver
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP and required modules
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - libapache2-mod-php
